### ISSUE TITLE
Radio button instead of checkbox

### ISSUE THREAD

**Issue by peterzadori** [stuttter/wp-user-groups#11]
Hi.

We are using your plugin on our website and we love it. It's really simple to use and it gives us nice control over users categorization.

However, we would like to have an option to attach user to just one group. So instead of checkboxes there will be radio buttons on edit screen.

Do you think it would be possible?

Thanks

**Comment by JJJ** [comment]
Sure!

**Comment by JJJ** [comment]
Done, I think! 💯
