### ISSUE TITLE
Undefined index 'exclusive' on edit user page

### ISSUE THREAD

**Issue by JoelLisenby** [stuttter/wp-user-groups#12]
At /wp-admin/profile.php or /user-edit.php?user_id=###

Notice: Undefined index: exclusive in /nas/content/live/pcics/wp-content/plugins/wp-user-groups/wp-user-groups/includes/classes/class-user-taxonomy.php on line 753

**Comment by JoelLisenby** [comment]
I have submitted a pull request with one way to resolve this issue https://github.com/stuttter/wp-user-groups/pull/13

**Comment by JJJ** [comment]
Awesome. Thank you!
