### ISSUE TITLE
Add ability to get users of a group with a certain role

### ISSUE THREAD

**Issue by desrosj** [stuttter/wp-user-groups#15]
`wp_get_users_of_group()` allows you to retrieve a list of users for a specific user group. But, there is no way to specify a subset of those users.

**Example:** I want to get a list of all users with the editor role in a user group. 

It would be great if `wp_get_users_of_group()` also accepted `WP_User_Query` arguments.

**Comment by JJJ** [comment]
PR looks good. I'll test and get it into 3.0.0.

Thanks!

**Comment by JJJ** [comment]
Merged to `master`. Will be in the next release (after 2.3.0 that I just shipped today.)
