### ISSUE TITLE
Bulk Assignment Error

### ISSUE THREAD

**Issue by benjibee** [stuttter/wp-user-groups#18]
I’ve set this plugin up on a client’s site, and they happily added 350+ users and 15+ groups only to run into an error with bulk group assignment.

To reproduce this error, I simply need to select multiple users, select “Add to [name] Group” and click “Apply” to see the page reload with no apparent changes having taken place.

Where do I even begin with this issue?

WordPress 4.9.6 using WP User Groups 2.1.1

https://wordpress.org/support/topic/bulk-assignment-error/

Also: sorry about the goats 😢

**Comment by wintermoor** [comment]
Same here with Plugin Version: 2.2.0 on WordPress Multisite, Version 4.9.7. 
Single group assignment is working fine, only bulk isn't working (like above). 

Would be glad if you can help ;)

**Comment by benjibee** [comment]
@wintermoor @JJJ I've attempted to diagnose this issue myself to no avail. Have you had any luck finding a fix? My client now has hundreds of users tied into this and I'm not sure how I can transition them to another plugin without a huge headache from all sides :(

**Comment by wintermoor** [comment]
No. I changed to "Groups"-plugin from https://de.wordpress.org/plugins/groups/ 
It works! 

Maybe you can use the plugin "Import users from CSV with meta": Just export your users and import them back with meta fields like groups. You only need to know which column heads are needed in CSV. You can decide whether to import duplicate users (you won't like to) or to update existing users.

**Comment by chrisvanpatten** [comment]
I looked a bit at this and it's an issue with the nonce verification failing — the nonce doesn't appear to be available when the `verify_nonce` method fires inside `handle_bulk_actions`.

**Comment by JJJ** [comment]
Just pushed 2.3.0 to fix this. Sorry for the delay.

Reopen if I broke something else. 💯
