### ISSUE TITLE
Array of ints are re-cast to strings in `wp_set_terms_for_user`

### ISSUE THREAD

**Issue by chrisvanpatten** [stuttter/wp-user-groups#19]
`wp_set_terms_for_user` runs the array of `$terms` through `sanitize_key`:

https://github.com/stuttter/wp-user-groups/blob/master/wp-user-groups/includes/functions/common.php#L74

This causes an array of `(int) term_id`s to be cast to strings, which in turn causes `wp_set_object_terms` to add new terms with the IDs as the term names.

**Comment by JJJ** [comment]
Confirmed.

I wonder if we are better off removing that line, and letting `wp_set_object_terms()` sort it out entirely?
