### ISSUE TITLE
Improve localizeabilty

### ISSUE THREAD

**Issue by ms-studio** [stuttter/wp-user-groups#3]
I had to localize the plugin for another language, and here are some suggestions to make it easier to localise:

## 1 : add load_theme_textdomain()

Currently the plugin doesn't load translations, even if po/mo files are present in /wp-content/languages/plugins. 

When I add the plugin_name_load_plugin_textdomain() function from https://ulrich.pogson.ch/load-theme-plugin-translations they work fine.

## 2 : make all strings localize-able

There's a series of strings that aren't localizable yet: https://github.com/stuttter/wp-user-groups/blob/4014df0a165a2bf23d421044ec666311d785c174/includes/class-user-taxonomy.php#L595

## 3 : add it to glotpress

The plugin hasn't been pushed into glotpress yet: https://translate.wordpress.org/projects/wp-plugins/wp-user-groups - perhaps you can ask for it on the polyglots site (and add me in as editor of the French locale): https://make.wordpress.org/polyglots/

Cheers !

**Comment by johnjamesjacoby** [comment]
PR accepted. Thank you!

**Comment by ms-studio** [comment]
You're welcome!
