### ISSUE TITLE
Can't retrieve users childs and users belongs to specific group

### ISSUE THREAD

**Issue by viceamiral** [stuttter/wp-user-groups#5]
Hi,
First I would like to thank you for this powerfull plugin.
Please I want to know how to retrieve a liste of users belong to a specefic group, I need that in order to fetch a list of user childs.
This methode I am using returns error :  
<code>
$ids_of_complete_users = get_objects_in_term(
  35 , // this is the id of my "profile-complete" group
  'user-group'
);

var_dump($ids_of_complete_users);
</code>

It returns this error : 
<code>
object(WP_Error)[1566]
  public 'errors' => 
    array (size=1)
      'invalid_taxonomy' => 
        array (size=1)
          0 => string 'La taxinomie est invalide' (length=25)
  public 'error_data' => 
    array (size=0)
      empty
</code>

I would be very appreciated if you could help me. Thank You

**Comment by johnjamesjacoby** [comment]
Something like:

```
/**
 * Return array of users in a group
 */
function get_users_of_group( $args = array() ) {

	// Parse arguments
	$r = wp_parse_args( $args, array(
		'taxonomy' => 'user-type',
		'term'     => 'student',
		'term_by'  => 'slug'
	) );

	// Get user IDs in group
	$term     = get_term_by( $r['term_by'], $r['term'], $r['taxonomy'] );
	$user_ids = get_objects_in_term( $term->term_id, $r['taxonomy'] );

	// Bail if no users in this term
	if ( empty( $term ) || empty( $user_ids ) ) {
		return array();
	}

	// Return queried users
	return get_users( array(
		'orderby' => 'display_name',
		'include' => $user_ids
	) );
}
```

**Comment by johnjamesjacoby** [comment]
I'll add a helper function for this in a future release.

**Comment by ms-studio** [comment]
Nice example! Indeed a helper function could be handy.

FWIW, here's how I'm doing things on a current project:

```php
$ids_of_complete_users = get_objects_in_term( 
  42, // id of group
  'user-group' 
);

// then
if (!empty($ids_of_complete_users)) {
  $user_query = new WP_User_Query( array( 
    'include' => $ids_of_complete_users, 
    'orderby' => 'registered',
    'order' => 'DESC'
  ) );
  if ( !empty( $user_query->results ) ) {
    foreach ( $user_query->results as $user ) {
    // display what is needed
    }
  }
}
```
