### ISSUE TITLE
Set Term User function doesn't work

### ISSUE THREAD

**Issue by hlaporthein** [stuttter/wp-user-groups#9]
Hello there,

Firstly, your plugin is so cool! :) . I love it. i would like to use your plugin functions after user register. For example

After I called `**wp_insert_user()**` for specific user and I called your functions `**wp_set_terms_for_user(1,'user-group',array('acf','brac','care'), false);
**` . I have no idea why it didn't save. 

As much as I understand that function, it also must work even I added it at the bottom of functions.php file. like below.

`**wp_set_terms_for_user(1,'user-group',array('acf','brac','care'), false);
**`

**Comment by JJJ** [comment]
Sorry about this. There was a problem with the capability check in that function causing it to prematurely exit. This is fixed now, and will go out with the next release.
